# fly.toml app configuration file generated for dupdetector-bot on 2023-04-23T20:52:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dupdetector-bot"
primary_region = "waw"

[[mounts]]
  source = "vitebsk_bot"
  destination = "/app/data"

[env]
  GOOGLE_APPLICATION_CREDENTIALS = "/app/data/service-key.json"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
