DB_NAME = "app.db"
SQLALCHEMY_TRACK_MODIFICATIONS = True
BOT_NAME = "vitebsk_bot"
BOT_TOKEN = ""

#openai
OPENAI_ORGANIZATION = "org-DoSOUBT1gIASAWhJm8DRNmVI"
OPENAI_TOKEN = ""

#bing
BING_SUBSCRIPTION_KEY = ""