"""Added tags and text fields to db.

Revision ID: a223e0599e2b
Revises: 11f0f1ac17b2
Create Date: 2023-04-25 16:06:34.732476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a223e0599e2b'
down_revision = '11f0f1ac17b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('tags', sa.String(length=1000), nullable=True))
    op.add_column('image', sa.Column('recognizedText', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'recognizedText')
    op.drop_column('image', 'tags')
    # ### end Alembic commands ###
