"""initial

Revision ID: db5be0cc1658
Revises: 
Create Date: 2025-02-10 09:43:45.707968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5be0cc1658'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dementiaRating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.String(length=64), nullable=False),
    sa.Column('userId', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phash', sa.String(length=64), nullable=False),
    sa.Column('msgId', sa.String(length=64), nullable=False),
    sa.Column('authorId', sa.String(length=64), nullable=False),
    sa.Column('chatId', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('msgId', sa.String(length=64), nullable=False),
    sa.Column('authorId', sa.String(length=64), nullable=False),
    sa.Column('chatId', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('image')
    op.drop_table('dementiaRating')
    # ### end Alembic commands ###
